name: nginx-autobuild
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for the image'
        required: true
        default: '1.19.1-alpine-ag-1.1'
jobs:
  deploy:
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Set image tag value basis input or git tag
      id: tagstep
      run: |
        if [ "${{ github.event.inputs.tag }}" != "" ]; then
          echo ::set-output name=tag::${{ github.event.inputs.tag }}
        else
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        fi
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0
      with:
        platforms: amd64,arm64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master
      id: buildx
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=registry,ref=user/app:latest
        cache-to: type=inline
        tags: |
          ghcr.io/${{ github.repository_owner }}/app:latest
          ghcr.io/${{ github.repository_owner }}/app:${{ steps.tagstep.outputs.tag }}
